name: Deployment

on:
  push:
    tags: "v*"

jobs:
  release:
    name: Build and create release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get tag
        run: echo ::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}
        id: get_tag

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Publish package on NPM
        run: pnpm publish --access public --no-git-checks

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
